<a href="https://colab.research.google.com/github/valeriaustenko/Data-Science-Course-USURT/blob/master/tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import copy

# 100 практических задач с python
<p>Курс "Модели и методы интеллектуального анализа данных"</p>
<p>Чернышов Юрий</p>
<p>к.ф.-м.н., доцент кафедры ИТЗИ УрГУПС (Екатеринбург)</p>
<p>yuchernyshov@usurt.ru</p>

# Оглавление <a name='toc'>
    
<ol>
<li><a href='#intro'>Введение</a></li>
<li><a href='#101'>10 простых алгоритмов</a></li>
<li><a href='#sort'>Сортировка</a></li>
<li><a href='#ML'>Машинное обучение</a></li>
<li><a href='#genetics'>Генетические алгоритмы</a></li>
<li><a href='#links'>Ссылки</a></li>
</ol>


# Введение <a name='intro'></a>

Язык Python был создан в 1991 году. В настоящее время интерес к использованию Python возрос в связи с большим количеством разработанных специализированных библиотек для отдельных задач, многочисленным сообществом разработчиков, а также применением Python для важных практических задач: математического моделирования, научных исследований, обработки данных и пр. Python является одним из основных инструментов при решении задач машинного обучения.

Python - интерпретируемый язык программирования. Программа Python (также используется термин скрипт) состоит из команд, которые последовательно выполняются интерптетатором Python.

Python проигрывает в скорости выполнения программ компилируемым языкам программирования (например, C), но имеет ряд преимуществ - наглядность, простота, лаконичность, популярность. Для быстрого предварительного исследования, моделирования, проверки гипотез, визуализации использование Python предпочтительнее.

Документ состоит из 100 сложных задач, решаемых с помощью Python и соответствующих библиотек.

Для удобства задачи разбиты на группы, к которым можно быстро перейти через <a href='#toc'>Оглавление</a>.

<a href='#toc'>Назад к Оглавлению</a>

# 10 простых алгоритмов <a name='101'></a>

### 1 Присваивание переменной 

На вход подается два числа. Нужно вывести сумму чисел.

In [ ]:
a = int(input()) 
b = int(input()) 
s = a + b 
print(s) 

7
8
15


### 2 Использование условия if

Даны два числа. Найти меньшее из них  и вывести его.

In [ ]:
a = int(input())  
b = int(input()) 
if a < b:  
    print(a)  
else:
    print(b)

7
8
7


### 3 Вычисления

На вход подается действительное число. Вывести дробную часть числа.

In [ ]:
x = float(input()) 
print(round(x - int(x),3)) 

### 4 Использование Цикла for

На вход подается два числа. Вывести последовательность чисел от А до B включительно.

In [ ]:
a = int(input())
b = int(input())
for i in range(a, b + 1):
    print(i)

### 5 Строки

Использование среза строки

In [ ]:
s = 'helloworld' 
print(s[1])     #выведет e
print(s[-1])    #выведет d
print(s[1:3])   #выведет el
print(s[1:-1])  #выведет elloworl      
print(s[:3])    #выведет hel  
print(s[2:])    #выведет lloworld  
print(s[:-1])   #выведет helloworl  
print(s[::2])   #выведет hlool
print(s[1::2])  #выведет elwrd
print(s[::-1])  #выведет dlrowolleh

e
d
el
elloworl
hel
lloworld
helloworl
hlool
elwrd
dlrowolleh


### 6 Использование цикла While

По данному целому числу найти все квадраты натуральных чисел, не превосходящие это число, в порядке возрастания.

In [ ]:
n = int(input())
i = 1
while i**2 <= n:
  print(i**2)
  i +=1

### 7 Использование списков

Вывести все элементы списка с четными индексами.

In [ ]:
a = input().split()
for i in range(0,len(a),2):
    print(a[i])

### 8 Применение функции

Вычислить факториал числа используя функцию.

In [ ]:
def factorial(n):
    res = 1
    for i in range(1, n + 1):
        res *= i
    return res

print(factorial(5)) #выведет 120
print(factorial(8)) #выведет 40320

### 9 Использование множеств
Даны два списка чисел. Вывести числа, входящие в оба списка.

In [ ]:
A = {1, 2, 3}
B = {3, 2, 3, 1}
res = A.union(B)
print(res)

{1, 2, 3}


### 10 Исползование словарей

Создание словаря и добавление новой записи.

In [ ]:
student = {}
s = "Ivanov Ivan Ekaterinburg USURT 5 5 4 5 3"
s = s.split()
student['LastName'] = s[0]
student['Name'] = s[1]
student['City'] = s[2]
student['University'] = s[3]
student['Marks'] = []
for i in s[4:]:
  student['Marks'].append(int(i))
print(student)


<a href='#toc'>Назад к Оглавлению</a>

# Сортировка <a name='sort'></a>

#### Пузырьковая сортировка

#### Сортировка выбором

#### Пирамидальная сортировка

<a href='#toc'>Назад к Оглавлению</a>

# Алгоритмы оптимизации <a name='optimization'></a>

#### Венгерский алгоритм

#### Задача об укладке рюкзака

#### Транспортная задача

#### Задача коммивояжера

<a href='#toc'>Назад к Оглавлению</a>

# Машинное обучение <a name='ML'></a>

<a href='#toc'>Назад к Оглавлению</a>

# Генетические алгоритмы <a name='genetics'></a>

#### Создать алгоритм, который находит строку заданной длины, имеющей максимальную сумму цифр строки.

In [ ]:
# длина строки
l = 1000

# размер популяции
n = 1000

population = np.array([[np.random.choice([0, 1]) for i in range(l)] for j in range(n)])

In [ ]:
population.shape

(1000, 1000)

In [ ]:
class Population():
    
    def __init__(self, length, size):
        self.length = length
        self.size = size
        self.population = np.array([[np.random.choice([0, 1]) for i in range(length)] for j in range(size)])
        
    def choice(self):
        pass

    def cross(self):
        pass
    
    def cross(self):
        pass

    def mutation(self):
        pass
    
    def __str__(self):
        return "Class Population"

In [ ]:
def selection(s):
    tmp = []
    m = 0
    for i in range(s.shape[0]):
        m += np.sum(s[i,:])
    m /= s.shape[0]
    for i in range(s.shape[0]):
        if np.sum(s[i,:]) >= m:
            tmp.append(s[i,:])
    return np.array(tmp)
        

In [ ]:
result = copy.deepcopy(population)

In [ ]:
%%time

for _ in range(100):
    result = selection(result)


CPU times: user 1.52 s, sys: 8.02 ms, total: 1.52 s
Wall time: 1.52 s


In [ ]:
print(result.shape)

(1, 1000)


In [ ]:
sorted(population, key=lambda x: np.sum(x), reverse=True)[:5]

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

<a href='#toc'>Назад к Оглавлению</a>

# Ссылки <a name='links'></a>

http://www.matplotlib.org - официальная страница проекта matplotlib.

https://colab.research.google.com/ - интерактивная среда для программирования на python

<a href='#toc'>Назад к Оглавлению</a>